### ISSUE TITLE
very interested in this project

### ISSUE THREAD

**Issue by stern0m1** [ernacktob/esp8266_wifi_raw#6]
Hi,
I am very interested in this project but i need help implementing.
I believe this project can solve a big issue for me. 
The low level details are a bit beyond me.
I program the esp8266 with the arduino ide and dont really have a good understanding of the internal workings.
I know how to use the standard promiscuous mode.

If someone could help me implement this I would greatly appreciate it.
An example that would work with the arduino core I guess, would help.

Thanks
B Hirsch

**Comment by ernacktob** [comment]
Hello,
What specifically do you need help with? The code in this project is for the ESP8266, but I haven't worked with ESP8266 and Arduino at the same time. Also note that there may be newer SDK versions, this project was only tested for sdk 1.2.0 and 0.9.3.

**Comment by stern0m1** [comment]
Im not sure where to start...
Do I need to first compile the patched files to .o object file and then .a file?
or can I just #include the hacked files? 
Thanks!

**Comment by ernacktob** [comment]
I assume the files you refer to are the ones coming with the esp8266 SDK (libpp.a, libnet80211.a, etc). You don't need to compile these or do anything else with them, as they are already given by the SDK.

Originally the method I was using to overload the libpp.a functions was by manually patching the symbol table in the binaries with a text editor. Pretty messy. But now we have a better method that was proposed by tgoddard in a previous issue: https://github.com/ernacktob/esp8266_wifi_raw/issues/1. This was implemented by redfast00 (see this issue: https://github.com/ernacktob/esp8266_wifi_raw/issues/4) and appears to be working.

So now the only think that you need to do is run the compile_and_flash.sh script or directly 'make' the Makefile. No need to touch the original sdk binaries.

**Comment by stern0m1** [comment]
I dont really know how to "make" for esp8266. I just use the arduino ide.
Is it possible to post compiled files?
Also, to implement in code, do i just use the regular promiscuous call back or is there some other callback?
 Thanks!
hirsch098@gmail.com

**Comment by ernacktob** [comment]
I am not familiar with using the Arduino IDE to program the esp8266. Do you have some project template or setup I could look at to have a better idea of what you are doing?

For the promiscuous callbacks: in this project you can hook your own callback by calling wifi_raw_set_recv_cb(your_function_name) (see user_main.c in line 122 for an example).

When I was working with the ESP8266 I was directly programming it using the tools in the esp_iot_sdk which can be downloaded from Espressif or Github. The binaries are in the lib/ folder. I assume the Arduino IDE would also come with these files available somewhere if it supports ESP8266.

Also note that it's been a few years since I've worked with the esp8266, I forgot a lot of stuff probably by now...

**Comment by stern0m1** [comment]
Thanks for your help! I really appreciate it. I'll be in touch tomorrow night.
If you don't mind I would like to be in touch directly via email.

**Comment by stern0m1** [comment]
Hi,
The files in include fodder are they the hacked files from the espressif sdk?

Thanks

**Comment by ernacktob** [comment]
Those are used to provide definitions for structs used by the lwIP TCP/IP stack. In particular because in wifi_raw.c we call ieee80211_output_pbuf() which requires a struct netif and a struct pbuf for its arguments (found by reverse-engineering experiments).

Normally these files are not needed if you only use the public API from Espressif's SDK.

**Comment by stern0m1** [comment]
Isee duplicate header files. For example opt.h is in 
esp8266_wifi_raw/include/
esp8266_wifi_raw/include/lwip/
Is there any reason why?
Thanks

**Comment by ernacktob** [comment]
To be honest I don't know. Everything in the include/ folder I copied from another place but unfortunately I forgot where I got it from. I haven't really touched any of the files in that folder, I only have them in order to get the struct pbuf and struct netif definitions...

**Comment by stern0m1** [comment]
https://github.com/emelianov/esp8266_wifi_raw

I had someone port it to arduino esp8266.
The most im getting is 163 bytes any ideas why? I understand to beacons and probe requests that are broadcast i should be getting the whole thing...

EDIT: After running for a long time I am getting more bytes. I need to study it more...

**Comment by stern0m1** [comment]
Using the sample code all my frames start with 40 (hex) which I believe means a probe request. I am not getting any beacons. Any idea why?
40 in hex  = 0100 0000.
Thanks

**Comment by jhon-paul-v** [comment]
Hi Stern0m1,I have the same problem about getting no beacons. Do you solve it now?

> Using the sample code all my frames start with 40 (hex) which I believe means a probe request. I am not getting any beacons. Any idea why? 40 in hex = 0100 0000. Thanks
